In [2]:
import numpy as np

# Array concatenation
here we have separate RGB channels of an image, concatenate them using `np.concatenate` and `np.stack` separately

In [2]:
h, w = 224, 224
R = np.random.randint(0, 256, size=(h, w))
G = np.random.randint(0, 256, size=(h, w))
B = np.random.randint(0, 256, size=(h, w))
R , G , B

(array([[ 92,  84,  80, ...,  93, 219,  83],
        [131, 150,  63, ...,  56, 243, 109],
        [164,  92,  38, ...,   4, 137,  92],
        ...,
        [206, 166,  86, ..., 103, 151,  14],
        [159, 184, 232, ..., 107,   1, 100],
        [  5,  68,  17, ...,  56, 113, 244]]),
 array([[ 70, 158, 247, ..., 236, 156,  90],
        [205,  62,  62, ..., 143,  70, 220],
        [251, 129, 124, ...,  17, 170, 127],
        ...,
        [ 49, 228, 218, ..., 254,  55, 234],
        [155,  49,  89, ...,  55, 156, 131],
        [142,  98, 160, ...,   7,  46,   1]]),
 array([[173, 231, 121, ..., 255,  54, 105],
        [197, 163,  61, ...,  61,  68, 238],
        [252,  68, 126, ..., 125,  35, 255],
        ...,
        [ 10, 228, 122, ...,  22, 235, 208],
        [138,  83, 163, ..., 155, 202,  79],
        [244, 226, 100, ..., 145,  15, 255]]))

In [3]:
# your code here #
colored = np.concatenate((R,G,B), axis = 0)
print(colored.shape)
colored

(672, 224)


array([[ 92,  84,  80, ...,  93, 219,  83],
       [131, 150,  63, ...,  56, 243, 109],
       [164,  92,  38, ...,   4, 137,  92],
       ...,
       [ 10, 228, 122, ...,  22, 235, 208],
       [138,  83, 163, ..., 155, 202,  79],
       [244, 226, 100, ..., 145,  15, 255]])

In [4]:
colored = np.stack((R,G,B),axis=0)
colored

array([[[ 92,  84,  80, ...,  93, 219,  83],
        [131, 150,  63, ...,  56, 243, 109],
        [164,  92,  38, ...,   4, 137,  92],
        ...,
        [206, 166,  86, ..., 103, 151,  14],
        [159, 184, 232, ..., 107,   1, 100],
        [  5,  68,  17, ...,  56, 113, 244]],

       [[ 70, 158, 247, ..., 236, 156,  90],
        [205,  62,  62, ..., 143,  70, 220],
        [251, 129, 124, ...,  17, 170, 127],
        ...,
        [ 49, 228, 218, ..., 254,  55, 234],
        [155,  49,  89, ...,  55, 156, 131],
        [142,  98, 160, ...,   7,  46,   1]],

       [[173, 231, 121, ..., 255,  54, 105],
        [197, 163,  61, ...,  61,  68, 238],
        [252,  68, 126, ..., 125,  35, 255],
        ...,
        [ 10, 228, 122, ...,  22, 235, 208],
        [138,  83, 163, ..., 155, 202,  79],
        [244, 226, 100, ..., 145,  15, 255]]])

# Array creation
`p` is a 1D array indicating probability of being dog(y=1). let's say all samples are truly dog and we need to create a ground-truth array for loss computation (don't worry :) you don't need to implement loss function here). imagine you can't explicitly use any shape information for this matter.

In [16]:
num_samples = 100
p = np.random.rand(num_samples)
p

array([0.97981843, 0.77916653, 0.80006857, 0.66615806, 0.21370884,
       0.00948957, 0.82340404, 0.41285389, 0.01795226, 0.45230654,
       0.66320835, 0.53011605, 0.24882519, 0.17836756, 0.78836858,
       0.25502742, 0.62220776, 0.09133474, 0.83363074, 0.90505702,
       0.10090905, 0.82744895, 0.08897054, 0.5880146 , 0.80674929,
       0.03935063, 0.82429354, 0.14377697, 0.49937101, 0.10029992,
       0.76348966, 0.19127896, 0.57049633, 0.54138384, 0.03120983,
       0.2058282 , 0.16061757, 0.29340122, 0.62446025, 0.20762858,
       0.15757849, 0.94588365, 0.4221717 , 0.15173632, 0.74824684,
       0.58376361, 0.10215857, 0.17528155, 0.95468868, 0.24532418,
       0.49535461, 0.61263274, 0.4480714 , 0.59201449, 0.65085601,
       0.00716825, 0.0588338 , 0.50827317, 0.18196444, 0.47489021,
       0.00859688, 0.39320082, 0.3178174 , 0.76567807, 0.74267028,
       0.24219191, 0.33014975, 0.17744306, 0.08478187, 0.58212313,
       0.07999928, 0.12973399, 0.77790931, 0.22105924, 0.89803

In [18]:
y_gt = np.ones_like(p)
y_gt

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Data stats
`salary` is a 2D array denoting salaries of six employees during 100 months. let's say the manager asks you to analyze his/her employees by answering the following questions (`np.argmax`, `np.max`, `np.argwhere`, `np.median` and `np.percentile` could be helpful :) )

In [3]:
salary = np.random.randint(5, 150, size=(6, 100))
salary

array([[ 95,  37,  70,  12,  32,  49, 106, 126,  96,  43,  26, 142,  76,
         74,  17,  34, 123, 131,  47,  30,  69, 136,  19,   9, 104,  82,
         24, 133, 125, 101,  38,  86,  58, 141,  74,  63,  91,  22, 143,
        137,  17,  62,  53,  86,  31,  57,  71, 127,  76, 117,  74, 109,
         10, 128, 146,   6,  31,  63, 139, 131,  55, 113,  64, 131,  74,
         97, 130, 105,  34,   5, 149, 113,  38,  39,  73,  40, 125, 110,
        114,  71,  54,  66,  42, 108, 149,  94, 105,  76,  45,  85, 113,
         38,  33,  57,  73, 113, 104, 139,  49,  95],
       [ 59,  24,  11, 126, 143,  86, 142,   8,  66,  17,  89,  59, 114,
        106,  73,  63,  23,   6,  98, 106,  13,  95,  13,  94,  89,   8,
         55,  82,  64, 138,  68,  52,  20,  47,  77,  75, 127, 108,  37,
         20,  66,  99, 118,  77,  61, 114,  86,  71, 119,  90,  57,  33,
         14,  74, 117,  77,   6, 109,  70, 139, 111,  56,  62,  76,  55,
         98,  86,  15,  69,  40, 149, 139,  67,  35,  77, 102,  35,   

1. for the 2nd employee, most salary earned during a month and when

In [4]:
print(salary[1].max())
print(salary[1].argmax())

149
70


2. find the most salary earned, by whom and when (might be multiple employees in multiple times)

In [5]:
print(salary.max())
np.argwhere(salary == salary.max())

149


array([[ 0, 70],
       [ 0, 84],
       [ 1, 70],
       [ 2,  3],
       [ 2, 97],
       [ 3, 43],
       [ 4, 29],
       [ 4, 68],
       [ 5, 86]])

3. per employee, the median salary they earned

In [6]:
np.median(salary, 1)

array([74. , 73.5, 78. , 80. , 88.5, 77.5])

4. per employee, their 25th max salary they earned

In [7]:
# your code here
np.percentile(salary, 75, axis=1)

array([113.  , 108.  , 112.5 , 117.  , 114.5 , 111.25])

# Indexing (including boolean) and slicing
`salary` is salaries of six employees during a year. implement code for the following parts

In [12]:
salary = np.random.randint(5, 100, size=(6, 12))
salary

array([[93, 81, 97, 91, 61, 33, 95, 20, 98, 15, 31, 20],
       [92,  9, 70, 50, 54, 20, 17, 98, 13, 84, 84,  5],
       [22, 59, 18, 18, 93, 12, 14, 65, 69, 99, 67, 19],
       [92, 19, 41, 83, 14, 77, 66, 88, 59, 65, 87, 43],
       [73, 77, 18, 74, 53, 40, 26, 19, 77, 67, 60,  6],
       [15, 43, 74, 95, 10, 53, 99, 49, 24,  5, 58, 70]])

1. show the salary of all employees in second month

In [13]:
salary[:,1]

array([81,  9, 59, 19, 77, 43])

2. show the salary of 1st and 3rd employees in even months

In [14]:
salary[(0,1), 0:12:2]

array([[93, 97, 61, 95, 98, 31],
       [92, 70, 54, 17, 13, 84]])

3. show salary of 1st employee in 5th month, 2nd one in 11st, 3rd in 7th

In [15]:
salary[0,4] , salary[1,10] , salary[2,6]

(61, 84, 14)

4. one day boss comes and seems angry :) telling you the most salary someone can earn is 90 and asks you to shift the salaries more than that to it.

In [22]:
a = np.where(salary>90 , 90 , salary)
a

array([[90, 81, 90, 90, 61, 33, 90, 20, 90, 15, 31, 20],
       [90,  9, 70, 50, 54, 20, 17, 90, 13, 84, 84,  5],
       [22, 59, 18, 18, 90, 12, 14, 65, 69, 90, 67, 19],
       [90, 19, 41, 83, 14, 77, 66, 88, 59, 65, 87, 43],
       [73, 77, 18, 74, 53, 40, 26, 19, 77, 67, 60,  6],
       [15, 43, 74, 90, 10, 53, 90, 49, 24,  5, 58, 70]])

# Other utilities

1. create an array of 1000 samples in a linear form between 0 and 1 using `np.linspace` and check the difference of all two subsequent elements are close to 0.001

In [11]:
dataset = np.linspace(0,1 ,1000)
print(dataset)
print(np.allclose(np.diff(dataset), 0.001))

[0.         0.001001   0.002002   0.003003   0.004004   0.00500501
 0.00600601 0.00700701 0.00800801 0.00900901 0.01001001 0.01101101
 0.01201201 0.01301301 0.01401401 0.01501502 0.01601602 0.01701702
 0.01801802 0.01901902 0.02002002 0.02102102 0.02202202 0.02302302
 0.02402402 0.02502503 0.02602603 0.02702703 0.02802803 0.02902903
 0.03003003 0.03103103 0.03203203 0.03303303 0.03403403 0.03503504
 0.03603604 0.03703704 0.03803804 0.03903904 0.04004004 0.04104104
 0.04204204 0.04304304 0.04404404 0.04504505 0.04604605 0.04704705
 0.04804805 0.04904905 0.05005005 0.05105105 0.05205205 0.05305305
 0.05405405 0.05505506 0.05605606 0.05705706 0.05805806 0.05905906
 0.06006006 0.06106106 0.06206206 0.06306306 0.06406406 0.06506507
 0.06606607 0.06706707 0.06806807 0.06906907 0.07007007 0.07107107
 0.07207207 0.07307307 0.07407407 0.07507508 0.07607608 0.07707708
 0.07807808 0.07907908 0.08008008 0.08108108 0.08208208 0.08308308
 0.08408408 0.08508509 0.08608609 0.08708709 0.08808809 0.0890

2. increase value of `arr` by one in places provided by `indices`

In [12]:
arr = np.zeros(5)
indices = np.random.randint(0, 5, size=(1000))
arr , indices

(array([0., 0., 0., 0., 0.]),
 array([4, 0, 4, 2, 1, 2, 2, 1, 0, 0, 0, 4, 1, 3, 4, 2, 1, 3, 2, 2, 2, 2,
        0, 2, 3, 3, 3, 1, 3, 4, 3, 0, 0, 1, 0, 4, 0, 1, 3, 0, 0, 4, 0, 3,
        2, 4, 4, 2, 0, 1, 2, 4, 4, 2, 0, 0, 0, 0, 4, 2, 0, 2, 1, 3, 1, 3,
        3, 2, 1, 0, 4, 1, 2, 3, 4, 4, 0, 2, 2, 3, 2, 2, 0, 4, 3, 1, 0, 4,
        1, 1, 0, 0, 3, 1, 4, 2, 2, 4, 2, 0, 4, 2, 1, 4, 0, 3, 0, 0, 2, 0,
        1, 3, 3, 4, 2, 1, 0, 3, 1, 1, 2, 1, 3, 0, 2, 1, 3, 4, 1, 2, 3, 1,
        0, 0, 2, 0, 3, 2, 1, 4, 4, 1, 3, 2, 1, 3, 0, 1, 2, 3, 0, 3, 1, 4,
        3, 4, 4, 4, 2, 1, 4, 0, 1, 2, 3, 2, 1, 1, 0, 1, 0, 0, 4, 2, 3, 1,
        0, 0, 3, 3, 4, 2, 3, 4, 0, 2, 1, 1, 3, 4, 3, 1, 0, 4, 1, 3, 0, 4,
        2, 1, 0, 0, 4, 0, 3, 4, 0, 3, 0, 0, 4, 0, 1, 3, 2, 0, 4, 0, 3, 0,
        0, 4, 0, 2, 0, 2, 1, 4, 2, 2, 2, 3, 0, 3, 1, 1, 1, 2, 1, 2, 3, 0,
        1, 2, 0, 3, 2, 2, 4, 3, 2, 3, 3, 2, 0, 3, 3, 3, 4, 1, 1, 3, 2, 0,
        2, 4, 4, 0, 4, 4, 0, 2, 2, 1, 4, 3, 4, 4, 3, 3, 4, 2, 1, 0, 0, 1,
        

In [13]:
for element in indices:
    arr[element]+=1
arr

array([214., 202., 196., 196., 192.])

3. for `arr`, select the 4th and 5th axis of last dimension using both numpy indexing and ellipsis and check their value equality using `np.all`

In [36]:
arr = np.random.rand(10, 10, 10, 10, 10, 8)
arr.shape

(10, 10, 10, 10, 10, 8)

In [50]:
a = arr[:,:,:,...,:,-1]
b = arr[:,:,:,:,...,-1]
print((a==b).all())
print(a==b)



True
[[[[[ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    ...
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]]

   [[ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    ...
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]]

   [[ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    ...
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]]

   ...

   [[ True  True  True ...  True  True  True]
    [ True  True  True ...  True  True  True]
    [ True  True  True ...  True  Tru