In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

1. read array from text
2. save as npy
3. read from npy

In [16]:
text_path = './iris.data'

In [51]:
data = pd.read_csv(text_path, sep=",", header= None)
print(data)
data.shape

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]


(150, 5)

In [53]:
np_arr = data.to_numpy()
np_arr

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [55]:
type(np_arr)

numpy.ndarray

In [56]:
np_arr[0]

array([5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], dtype=object)

stack an array to matrix vertically and horizontally using hstack and vstack functions

In [65]:
a = np.random.randint(0,100,size=(3,3))
b = np.random.randint(0,100,size=(1,3))
print(a)
print()
print(b)

[[10 45 90]
 [98 72 60]
 [47 23 36]]

[[30 24 85]]


In [72]:
# horizontal stacking
vstack = np.vstack((a,b))
vstack

array([[10, 45, 90],
       [98, 72, 60],
       [47, 23, 36],
       [30, 24, 85]])

In [92]:
# vertical stacking
ha = np.hstack(a)
print(ha)
hb = np.hstack(b)
print(hb)
new = np.hstack((ha,hb))
new

[10 45 90 98 72 60 47 23 36]
[30 24 85]


array([10, 45, 90, 98, 72, 60, 47, 23, 36, 30, 24, 85])

replace items that satisfy a condition with another value

In [94]:
a = np.random.randint(0,100,size=(10,10))
a

array([[72, 65, 33,  2, 37, 19, 85, 40, 55, 28],
       [60,  0, 89, 94, 87, 51, 71, 84, 94, 51],
       [28, 70,  0, 48, 97, 67, 76, 85, 48, 42],
       [43, 44, 41,  2, 67, 74, 69, 79, 50, 93],
       [89, 45, 53, 67, 23, 89, 35, 89, 51, 74],
       [38, 34, 28, 10,  6, 51, 61,  1, 11, 13],
       [41, 29, 56, 91, 63, 81, 59, 51, 26, 27],
       [52,  6, 25, 98, 92,  2, 13, 45, 68, 96],
       [13, 20, 64, 18,  9, 40, 66,  2, 75, 69],
       [38,  8, 56,  5, 40,  1, 48, 79, 57,  7]])

In [95]:
# items bigger than 20 -> -1
a = np.where(a >20 , -1 ,a )
a

array([[-1, -1, -1,  2, -1, 19, -1, -1, -1, -1],
       [-1,  0, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1,  0, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1,  2, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, 10,  6, -1, -1,  1, 11, 13],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1,  6, -1, -1, -1,  2, 13, -1, -1, -1],
       [13, 20, -1, 18,  9, -1, -1,  2, -1, -1],
       [-1,  8, -1,  5, -1,  1, -1, -1, -1,  7]])

get the intersection between two python numpy arrays


In [100]:
a = np.arange(10)
b = np.arange(5) * 2
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
b

array([0, 2, 4, 6, 8])

In [102]:
intesection = a[np.in1d(a,b)]
intesection

array([0, 2, 4, 6, 8])

In [103]:
c= np.intersect1d(a, b)
c

array([0, 2, 4, 6, 8])

remove items of an array from another array

In [105]:
a = np.arange(10)
b = np.arange(5) * 2
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
b

array([0, 2, 4, 6, 8])

In [107]:
a = [i for i in a if i not in b]
a

[1, 3, 5, 7, 9]

extract all elements between a given range

In [108]:
a = np.arange(10)
# items between 5 and 10
a = np.where(np.logical_and(a>=5, a<=10))
a

(array([5, 6, 7, 8, 9]),)

change columns order in a 2d numpy array

In [110]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
a = np.arange(12).reshape((2,2,3))
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

count elements

In [132]:
a = np.random.randint(0,100,size=(10,10)) 
a

array([[21, 10,  3, 61, 17, 28, 67,  3, 35, 44],
       [10, 47, 50, 34,  5, 47, 18, 79, 19, 26],
       [11, 86, 22, 66, 67, 45, 92, 88, 54, 32],
       [56, 12, 29, 25, 68, 40, 65, 29, 72, 95],
       [93,  9, 86, 94, 69, 71, 53, 58, 63, 56],
       [72, 77, 80, 13, 80, 92, 79, 74, 35, 47],
       [67, 85, 59, 55, 47, 52, 30,  5, 13,  9],
       [16, 22, 19, 13, 32, 42, 12, 63, 90, 61],
       [73, 63, 73, 81,  8, 97, 65,  0, 38, 73],
       [48, 10,  2, 80, 46, 13, 78, 81,  3, 23]])

In [133]:
#count of each element
x = [element for row in a for element in row]

freq={}
for element in x:
    if element in freq:
        freq[element]+=1
    else:
        freq[element] = 1

freq

{21: 1,
 10: 3,
 3: 3,
 61: 2,
 17: 1,
 28: 1,
 67: 3,
 35: 2,
 44: 1,
 47: 4,
 50: 1,
 34: 1,
 5: 2,
 18: 1,
 79: 2,
 19: 2,
 26: 1,
 11: 1,
 86: 2,
 22: 2,
 66: 1,
 45: 1,
 92: 2,
 88: 1,
 54: 1,
 32: 2,
 56: 2,
 12: 2,
 29: 2,
 25: 1,
 68: 1,
 40: 1,
 65: 2,
 72: 2,
 95: 1,
 93: 1,
 9: 2,
 94: 1,
 69: 1,
 71: 1,
 53: 1,
 58: 1,
 63: 3,
 77: 1,
 80: 3,
 13: 4,
 74: 1,
 85: 1,
 59: 1,
 55: 1,
 52: 1,
 30: 1,
 16: 1,
 42: 1,
 90: 1,
 73: 3,
 81: 2,
 8: 1,
 97: 1,
 0: 1,
 38: 1,
 48: 1,
 2: 1,
 46: 1,
 78: 1,
 23: 1}

In [138]:
unique, counts = np.unique(a, return_counts=True)
dict(zip(unique, counts))

{0: 1,
 2: 1,
 3: 3,
 5: 2,
 8: 1,
 9: 2,
 10: 3,
 11: 1,
 12: 2,
 13: 4,
 16: 1,
 17: 1,
 18: 1,
 19: 2,
 21: 1,
 22: 2,
 23: 1,
 25: 1,
 26: 1,
 28: 1,
 29: 2,
 30: 1,
 32: 2,
 34: 1,
 35: 2,
 38: 1,
 40: 1,
 42: 1,
 44: 1,
 45: 1,
 46: 1,
 47: 4,
 48: 1,
 50: 1,
 52: 1,
 53: 1,
 54: 1,
 55: 1,
 56: 2,
 58: 1,
 59: 1,
 61: 2,
 63: 3,
 65: 2,
 66: 1,
 67: 3,
 68: 1,
 69: 1,
 71: 1,
 72: 2,
 73: 3,
 74: 1,
 77: 1,
 78: 1,
 79: 2,
 80: 3,
 81: 2,
 85: 1,
 86: 2,
 88: 1,
 90: 1,
 92: 2,
 93: 1,
 94: 1,
 95: 1,
 97: 1}

sort by column

In [145]:
a = np.random.randint(0,100,size=(10,10))
a

array([[55, 60,  5, 31, 64,  3, 45, 56, 36, 53],
       [63, 99, 66,  6, 85, 47, 16, 39, 24, 93],
       [69, 15, 80, 11, 74, 59, 72, 80, 75, 58],
       [72, 80,  0, 75,  3, 47, 26, 28, 47,  3],
       [94, 36, 35, 94, 25, 31, 55, 28, 49, 99],
       [22, 24, 65, 77, 44, 65, 64, 14, 51, 24],
       [44, 61, 29, 53,  2, 33, 90, 31, 29, 22],
       [46, 25, 52,  5, 32, 26, 31, 21, 34,  3],
       [18, 63, 16,  6, 11, 46, 17, 63, 32, 47],
       [36, 21, 69, 36, 97, 37, 12, 23, 43, 42]])

In [146]:
# sort based on column 3
a = a[a[:, 2].argsort()]
a

array([[72, 80,  0, 75,  3, 47, 26, 28, 47,  3],
       [55, 60,  5, 31, 64,  3, 45, 56, 36, 53],
       [18, 63, 16,  6, 11, 46, 17, 63, 32, 47],
       [44, 61, 29, 53,  2, 33, 90, 31, 29, 22],
       [94, 36, 35, 94, 25, 31, 55, 28, 49, 99],
       [46, 25, 52,  5, 32, 26, 31, 21, 34,  3],
       [22, 24, 65, 77, 44, 65, 64, 14, 51, 24],
       [63, 99, 66,  6, 85, 47, 16, 39, 24, 93],
       [36, 21, 69, 36, 97, 37, 12, 23, 43, 42],
       [69, 15, 80, 11, 74, 59, 72, 80, 75, 58]])

generate one hot encoding

In [167]:
a = np.random.randint(0,100,size=10)
a

array([82, 22, 46, 36, 43, 96, 44, 79, 51, 84])

In [164]:
b = np.zeros((a.size, a.max()+1))
b[np.arange(a.size),a] = 1
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.

numpy broadcasting . we have two arrays with shape [a] and [b]. we want to compute distance between each two elements using broadcasting

In [ ]:
a = np.random.randint(0,10,size=(7))
b = np.random.randint(0,10,size=(5))
# your code here

arithmetic operation

In [177]:
a = np.random.randint(0,100,size=(10,10))
b = np.random.randint(1,100,size=(10,10))
sub = np.subtract(a , b)
summ = np.add(a,b)
mul = np.multiply(a,b)
div = np.divide(a,b)
a , b , sub, summ, mul, div

(array([[18,  4, 99,  4,  6, 96, 82, 56, 47, 39],
        [28,  4, 99, 49, 34, 12, 77, 51, 70, 16],
        [28, 26, 96, 57, 23,  9,  5, 40, 72, 60],
        [97,  7,  1, 35, 50, 87, 54, 75, 28,  4],
        [82,  0, 41, 12, 12, 80, 14, 62, 98, 70],
        [61, 68, 11, 40, 63, 91, 85,  1, 25, 14],
        [ 9,  8, 62, 70, 55, 91, 26, 70, 50, 13],
        [87, 42, 97, 63, 61,  5, 96, 98, 42, 71],
        [83, 26, 36,  1, 26, 95,  6, 98, 16,  5],
        [91, 88, 61, 70, 84, 85, 28,  9, 38, 26]]),
 array([[86,  3, 65, 96, 62, 19, 39, 78, 60, 63],
        [48, 37, 38, 71, 37, 38, 56, 96, 79, 48],
        [12, 43, 68, 48, 59, 50, 88, 50,  3, 78],
        [76, 43, 83, 27, 98, 92, 20, 15, 45, 42],
        [32, 25, 10, 14, 53, 90, 35, 96, 69, 35],
        [ 3, 93, 10,  5, 37, 95, 17, 49, 75, 22],
        [99, 97, 12, 74, 58, 76, 98, 75, 25, 35],
        [44, 79, 52, 76,  5, 85, 97,  9, 91,  1],
        [ 9, 43, 34, 83, 29, 11,  3, 50, 73, 99],
        [94, 71, 82, 46, 42, 89, 77, 40, 73, 81]

max values of columns

In [180]:
a = np.random.randint(0,100,size=(10,10))
print(a)
#max of each column in an array
b = [np.max(row) for row in a]
print(b)

[[45 82  9  2 31 96 23 77 17 75]
 [86 49 59 69 90 80  5 10 82 12]
 [54 54 76 60  1 23 97 41  3 53]
 [61 32 69 97 29 64 73 92 59 24]
 [ 4 31 45 12 70 40 27 79 10 16]
 [57 78 26 69  1 35 48 17 93 47]
 [73 78 45 34 34 23 31 17 80 97]
 [82 42 86  3 44 47 41 50 57 13]
 [ 1 12 10 60 46 83 92 48  5 78]
 [82 15 24  0 85 33 31 55 55 83]]
[96, 90, 97, 97, 79, 93, 97, 86, 92, 85]


check array similarity using allclose function

In [182]:
a = np.random.randint(0,100,size=(10,10))
print(a)
b = a + np.random.rand(10,10) * 1e-6
print(b)
# if two matrix have closer values than a threshold return true  
c = np.allclose(a , b , 1e-2)
c

[[30 77 14 94 33 77 62 72 69 47]
 [98 48 25 29 96 72 24 94 18 68]
 [28 34 79 59 32 90 22 69 70 18]
 [65 16 25 69  2 85 39  8 39 64]
 [39 92 19 15 63 31 40 90 22 96]
 [34 28  4 52 32 95 39 11 64 25]
 [82 46 72 49 45 21 21 34 98 49]
 [66 56 34 66 28 91 34 97  6  2]
 [37 42 95 53 69 83 61 17 48 39]
 [83 28 52 60 84 76 90 80 52 14]]
[[30.00000055 77.00000041 14.00000093 94.00000054 33.00000051 77.00000088
  62.0000005  72.00000092 69.00000095 47.00000047]
 [98.00000032 48.00000015 25.00000017 29.00000037 96.00000057 72.0000002
  24.00000098 94.00000088 18.00000084 68.00000035]
 [28.00000062 34.00000053 79.0000008  59.00000041 32.00000099 90.00000033
  22.00000055 69.00000042 70.00000074 18.00000093]
 [65.0000009  16.00000006 25.00000033 69.00000041  2.00000011 85.00000032
  39.00000024  8.00000087 39.00000092 64.00000024]
 [39.00000074 92.00000025 19.00000098 15.00000079 63.00000013 31.00000014
  40.00000085 90.00000012 22.00000039 96.00000049]
 [34.00000079 28.00000026  4.00000045 52.0000

True

matrix multiplication

In [5]:
a = np.random.randint(0,100,size=(6,8))
b = np.random.randint(0,100,size=(8,10))
# return A x B and it's shape
c = np.dot(a,b)
print(c)
print(c.shape)
print(type(c))

c = a@b
print(c)
print(c.shape)
print(type(c))

[[15700 22416 22390 18951 14089 22217  7015 23933 25626 13620]
 [21725 31396 28963 23148 19181 34735 15704 26980 34325 17568]
 [22830 32551 28075 22060 24170 33214 14949 30040 30797 21983]
 [12816 16382 16426 13273 13275 15957  2969 21321 20057 11323]
 [18508 25309 22795 22413 20180 28262 13773 22187 20591 10212]
 [10230 13326 18491 12135  8877 17675  5142 11841 20545 11448]]
(6, 10)
<class 'numpy.ndarray'>
[[15700 22416 22390 18951 14089 22217  7015 23933 25626 13620]
 [21725 31396 28963 23148 19181 34735 15704 26980 34325 17568]
 [22830 32551 28075 22060 24170 33214 14949 30040 30797 21983]
 [12816 16382 16426 13273 13275 15957  2969 21321 20057 11323]
 [18508 25309 22795 22413 20180 28262 13773 22187 20591 10212]
 [10230 13326 18491 12135  8877 17675  5142 11841 20545 11448]]
(6, 10)
<class 'numpy.ndarray'>


compute rank of matrix using numpy.linalg

In [186]:
a = np.random.randint(0,100,size=(6,8))
np.linalg.matrix_rank(a)

6

compute matrix norm using numpy.linalg

In [187]:
a = np.random.randint(0,100,size=(6,8))
np.linalg.norm(a)

397.003778319552

compute matrix inverse using numpy.linalg

In [188]:
a = np.random.randint(0,100,size=(8,8))
np.linalg.inv(a)

array([[-0.00265489,  0.04499903, -0.02456606,  0.02519852, -0.02713322,
        -0.02218233,  0.00252206,  0.01453798],
       [ 0.00592221, -0.02717149,  0.04675972, -0.04152882,  0.02333931,
        -0.00272753, -0.00873349,  0.00397807],
       [-0.00252055,  0.00056469, -0.03372574,  0.0331677 , -0.0154771 ,
         0.01518707,  0.00823143, -0.004222  ],
       [ 0.00217215,  0.03332401, -0.06658155,  0.06618358, -0.01864919,
        -0.00691455,  0.00785182, -0.00267633],
       [ 0.0011945 ,  0.01081419, -0.00762565,  0.00227183,  0.00033399,
        -0.01648267,  0.01003684,  0.00693714],
       [ 0.01186308, -0.04539308,  0.06267442, -0.06269697,  0.02623276,
         0.01737678, -0.00744324, -0.01003482],
       [-0.00271832, -0.01459248,  0.03614412, -0.04861858,  0.01232101,
         0.00739628, -0.00945369,  0.01368565],
       [-0.00450073, -0.00858332,  0.01298406, -0.0029218 ,  0.01252941,
         0.00561196, -0.00204928, -0.01392101]])